"""empty message

Revision ID: 0e37faa4bcd4
Revises: 
Create Date: 2024-10-20 09:53:05.889883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e37faa4bcd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('async_result_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_async_task_id'), 'async_task', ['id'], unique=True)
    op.create_index(op.f('ix_async_task_status'), 'async_task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_async_task_status'), table_name='async_task')
    op.drop_index(op.f('ix_async_task_id'), table_name='async_task')
    op.drop_table('async_task')
    # ### end Alembic commands ###
