"""create task table

Revision ID: 9fc822059594
Revises: 
Create Date: 2024-10-21 02:57:13.795872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9fc822059594'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('task',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('task_name', sa.String(), nullable=False),
                    sa.Column('async_result_id', sa.String(), nullable=True),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('is_canceled', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=True)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
